alias ll='ls -al'
alias drush='sudo -u www-data drush'
alias svn='sudo -u www-data svn'
alias git='sudo -u www-data git'
alias wget='sudo -u www-data wget'
alias ssh='sudo -u www-data ssh'
if [ -f /var/www/html/php.ini ];then
  ln -s /var/www/html/php.ini /usr/local/etc/php/conf.d/000-php.ini
fi
if [ -f /var/www/html/php.ini ];then
  ln -s /var/www/html/php.ini /usr/local/etc/php/conf.d/000-php.ini
fi
